name: File Counter
description: Annotates the build with a file count
author: https://github.com/stephanieatte
requirements: []
configuration:
  properties:
    pattern:
      type: string
  additionalProperties: false

